project_id: '784710'
api_token_env: CROWDIN_API_TOKEN
preserve_hierarchy: true
languages_mapping: &languages_mapping
  two_letters_code:
    en: en
files:
  - source: /i18n/zh/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
    languages_mapping: *languages_mapping
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    languages_mapping: *languages_mapping
  - source: /blog/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%
    languages_mapping: *languages_mapping
