import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tools: [{
    type: 'category',
    label: 'ID在线生成',
    link: {
      type: 'generated-index',
      title: 'ID在线生成',
      description:
        "一些常用的id生成器",
      keywords: ['id', 'uuid', 'snowflake'],
      slug: '/id_gen'
    },
    items: [
      'tools/id_generator/uuid',
      'tools/id_generator/nanoid',
      'tools/id_generator/snowflakeid',
    ]
  },
    {
      type: 'category',
      label: '加解密',
      link: {
        type: 'generated-index',
        title: '加解密工具',
        description: "常用的加解密工具都在这里",
        keywords: ['md5', 'bcrypt'],
        slug: '/sec'
      },
      items: [
        'tools/endecryption/md5',
        'tools/endecryption/sha',
        'tools/endecryption/digest',
        'tools/password_generator/password_generator',
        'tools/password_complexity_calculator/password_complexity_calculator'
      ]
    },
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
